security_logout:
    path: /logout
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
tickets:
    resource: "@AppBundle/Controller/Api/TicketsController.php"
    type:     rest
    prefix:   /api
categories:
    resource: "@AppBundle/Controller/Api/CategoriesController.php"
    type:     rest
    prefix:   /api
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
