security:
  providers:
    in_memory:
      memory:
        users:
          admin:
            password: admin
            roles: ROLE_ADMIN
          worker:
            password: worker
            roles: ROLE_WORKER

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      anonymous: ~
      http_basic: ~
      logout:
        path: security_logout
        target: homepage

  access_control:
    - { path: ^/admin, roles: ROLE_WORKER }
    - { path: ^/admin/users, roles: ROLE_ADMIN }

  role_hierarchy:
    ROLE_WORKER: ROLE_USER
    ROLE_ADMIN: [ROLE_WORKER]

  encoders:
    Symfony\Component\Security\Core\User\User: plaintext