services:
    category.service:
        class: AppBundle\Service\CategoryService
        arguments: ["@doctrine"]
    ticket.service:
        class: AppBundle\Service\TicketService
        arguments: ["@doctrine"]
