services:
    category.service:
        class: AppBundle\Service\CategoryService
        arguments: ["@doctrine"]
    comment.service:
        class: AppBundle\Service\CommentService
        arguments: ["@doctrine"]
