AppBundle\Entity\Ticket:
    exclusion_policy: ALL
    properties:
        id: { type: "integer", groups: [details, update], expose: true }
        description: { type: "string", groups: [details], expose: true }
