AppBundle\Entity\Category:
    exclusion_policy: ALL
    properties:
        id: { type: "integer", groups: [details], expose: true }
        name: { type: "string", groups: [details], expose: true }
